### ISSUE TITLE
Adding `new Photon` in the lambda function context stops the engine 

### ISSUE THREAD

**Issue by timsuchanek** [prisma/photonjs#274] opened 2019-10-28 09:26 UTC
As of now, when having a lambda function like this:
```ts
import {Photon} from '@generated/photon'

const photon = new Photon()

export function handler() {
  return photon.users.findMany()
}
```

The child process of the query engine gets stopped as soon as the function stops. As soon as this function gets reused, I now get "Engine has stopped".

We need to investigate, how the freezing of a lambda function exactly triggers the engine to stop and how to prevent it.
One way would be to detect, that the code is running in a lambda context.

**Comment by divyenduz** [comment] 2019-12-09 11:13
Internal note: candidate from bug triaging meeting

**Comment by divyenduz** [comment] 2020-01-07 14:05
I couldn't reproduce this, the snippet demonstrates an non-async handler, which should be terminated with a `callback` function call or when the event loop is empty. 

If the function is async, promise may be returned. 

Since the snippet is not complete, I can't try it as is, but I believe that turning the handler into an `async` function should make it work. 

Relevant docs: https://docs.aws.amazon.com/lambda/latest/dg//nodejs-prog-model-handler.html

---

I don't completely understand how the prior one could lead to engine being stopped, it should just have been a lambda timeout. 

I would appreciate a reproducible snippet, trying things out till then.

**Comment by divyenduz** [comment] 2020-01-07 14:25
Spoke to Tim, I have tried scheduled events, http payload. 

Tim was trying it with AWS SDK function invocation (both sync and async failed), I will try it with aws sdk function invocation as well.

**Comment by divyenduz** [comment] 2020-01-08 15:47
I couldn't reproduce this with AWS SDK function invocation (sync, async), CLI invocation. 

Note that I used invocation both type Event and RequestResponse. 

Spoke to Tim, closing this for now, Tim will open a new issue if he runs into it again. 

Attempted reproduction: https://github.com/divyendu-test/p2-lambda-invocation

**Closed by divyenduz** 2020-01-08 15:47 UTC
Labels: bug/2-confirmed, kind/bug
