### ISSUE TITLE
`Field does not exist on enclosing type.` When using most filters (some, etc)

### ISSUE THREAD

**Issue by luhagel** [prisma/photonjs#222] opened 2019-09-11 00:02 UTC
Kind of a continuation of #190 
Currently, when trying to use `.findMany` in combination with nested `some: {}` selection causes photon to throw an `Invalid Invocation` error.
```
Reason: Error occurred during query validation & transformation:
[2] Query (object)
[2]   ↳ findManyEventGroup (field)
[2]     ↳ where (argument)
[2]       ↳ EventGroupWhereInput (object)
[2]         ↳ OR (field)
[2]           ↳ EventGroupWhereInput (object)
[2]             ↳ participants_some_id (field)
[2]               ↳ Field does not exist on enclosing type.
```

**Comment by pantharshit00** [comment] 2019-09-13 10:43
I can confirm this with both the latest stable version(``) and the latest alpha version(`prisma2@2.0.0-alpha.184, binary version: 408c0c08746064a56c8ba7cb167bad49f1d2c2f7`)

![image](https://user-images.githubusercontent.com/22195362/64856113-e9c79b80-d63e-11e9-8595-0c2eee401860.png)


Reproduction: https://github.com/harshit-test-org/prisma-photon-222

**Comment by luhagel** [comment] 2019-09-20 22:59
Quick update, after playing around with Harshit's repro repo, I can confirm that this problem exists for pretty much all of the filter methods not already solved individually (`notIn` etc)

Could you take a look at all the current filters and make sure photon knows how to forward them to the query engine? [Nik recently updated the nested write/read docs](https://github.com/prisma/prisma2/blob/master/docs/relations.md) and used `startsWith`, which currently doesn't work either.

Confirmed not working:
* some
* every
* none
* beginsWith
* endsWith
* probably others I forgot to test

**Comment by timsuchanek** [comment] 2019-10-15 14:03
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.

**Closed by timsuchanek** 2019-10-15 14:03 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by iherger** [comment] 2019-10-19 08:09
@timsuchanek, this works for me locally (MacOS).

However, on dokku/Heroku, the same query (using `some` in the filter) fails with the following error:
```
2019-10-19T08:00:33.347278374Z app[web.1]: { GraphQLError: Error in Photon:
2019-10-19T08:00:33.347464799Z app[web.1]: Error: Reason: Error occurred during query validation & transformation:
2019-10-19T08:00:33.347550779Z app[web.1]: Query (object)
2019-10-19T08:00:33.347622041Z app[web.1]:   ↳ findManyEvent (field)
2019-10-19T08:00:33.347688905Z app[web.1]:     ↳ where (argument)
2019-10-19T08:00:33.347763185Z app[web.1]:       ↳ EventWhereInput (object)
2019-10-19T08:00:33.347815993Z app[web.1]:         ↳ AND (field)
2019-10-19T08:00:33.347882522Z app[web.1]:           ↳ EventWhereInput (object)
2019-10-19T08:00:33.347934923Z app[web.1]:             ↳ staff_some_user (field)
2019-10-19T08:00:33.347999918Z app[web.1]:               ↳ Field does not exist on enclosing type.
```
Photon debug output:
```
2019-10-19T07:59:54.801094560Z app[web.1]: 2019-10-19T07:59:54.800Z getos { version: 'OpenSSL 1.1.1  11 Sep 2018\n' }
2019-10-19T07:59:54.802022498Z app[web.1]: 2019-10-19T07:59:54.801Z getos { ls: '' }
2019-10-19T07:59:54.803170339Z app[web.1]: 2019-10-19T07:59:54.802Z getos { version: 'OpenSSL 1.1.1  11 Sep 2018\n' }
2019-10-19T07:59:54.803808484Z app[web.1]: 2019-10-19T07:59:54.803Z getos { ls: '' }
2019-10-19T07:59:54.808082251Z app[web.1]: 2019-10-19T07:59:54.807Z getos { platform: 'linux', libssl: '1.1.1' }
2019-10-19T07:59:54.808798941Z app[web.1]: 2019-10-19T07:59:54.808Z getos { platform: 'linux', libssl: '1.1.1' }
```

**Comment by pantharshit00** [comment] 2019-10-30 13:09
@iherger 

Can you please make sure that you are using the latest version? I was unable to reproduce this

**Comment by iherger** [comment] 2019-10-30 13:13
@pantharshit00 , thanks for following up. It is actually working now, also on Heroku.

**Comment by kenule500** [comment] 2020-05-17 00:57
am using 2.0.0-alpha.1217  but still not working for me

**Comment by pantharshit00** [comment] 2020-05-17 03:44
@kenule500 Please open a new issue with a minimal reproduction

**Comment by SteedMonteiro** [comment] 2020-08-19 17:39
try to update @prisma/cli and @prisma/client to the same version. I had the issue and it fixed it.
