### ISSUE TITLE
Error: EROFS

### ISSUE THREAD

**Issue by iamkevinwolf** [prisma/photonjs#398] opened 2020-01-12 07:44 UTC
I am using [zeit now](https://zeit.co) to deploy a next.js application, using `apollo-server-micro` for `serverless apollo-server`, together with `prisma2` , `nexus` and `nexus-prisma`.

However, when I try to perform any call to photon, I receive the following error:

```
Error in Photon: Error: EROFS: read-only file system, chmod '/var/task/node_modules/@prisma/photon/runtime/query-engine-rhel-openssl-1.0.x' at Object.chmodSync (fs.js:1104:3) at Object.plusX (/var/task/node_modules/@prisma/photon/runtime/index.js:44447:18) at NodeEngine.getPrismaPath (/var/task/node_modules/@prisma/photon/runtime/index.js:3378:16) at async /var/task/node_modules/@prisma/photon/runtime/index.js:3412:36
```

I already installed `prisma2@alpha` and `@prisma/photon@alpha`, but I still get the same error.

This is part of my `schema.prisma`:

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator photon {
  provider = "photonjs"
}

model User {
  id          String       @default(cuid()) @id
  createdAt   DateTime     @default(now())
  updatedAt   DateTime     @updatedAt
  email       String       @unique
  password    String
  firstname   String
  lastname    String
}
```

And this is the mutation i'm trying to execute:

```
export const SignInMutation = mutationField('signIn', {
  type: 'String',
  args: {
    email: stringArg({ required: true }),
    password: stringArg({ required: true }),
  },
  resolve: async (_root, { email, password }, ctx) => {
    const user = await ctx.photon.users.findOne({ where: { email } })

    if (!user) {
      throw new Error('No existe ningún usuario con éste correo electrónico')
    }

    const passwordValid = await comparePassword(password, user.password)

    if (!passwordValid) {
      throw new Error('La contraseña es incorrecta')
    }

    return createToken(user)
  },
})
```

**Comment by pantharshit00** [comment] 2020-01-21 15:45
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/1170

**Closed by pantharshit00** 2020-01-21 15:45 UTC
