### ISSUE TITLE
Self nested collection adding error

### ISSUE THREAD

**Issue by aifedespaix** [prisma/photonjs#294] opened 2019-11-12 15:40 UTC
## What I tried to do

Hello !
I use prisma2 to develop a comment feature.
Comments should be commented.
The comment model is self calling

## Error

I get the following error
``` error
Oops, an unknown error occured! This is on us, you did nothing wrong.
Reason: called `Option::unwrap()` on a `None` value in src\libcore\option.rs:378:21
Please create an issue in the photonjs repo with
```

That's why I'm here.

## Prisma Schema

Actual schema looks like
``` prisma
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "postgresql"
  url = [...]
}

[...]

model Comment {
  id         String     @default(cuid()) @id
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  value      String
  author     User
  childs     Comment[]  @relation("comment_childs", onDelete: CASCADE)
  likes      Like[]
}

[...]

```

## Resolver
``` ts
return this.photonService.comments.update({
    where: {id: parentId},
    data: {
        childs: {
            create: {
                value,
                author: {connect: {id: user.id}}
            }
        }
    },
});
```

## Main dependencies
``` json
{
  "prisma2": "^2.0.0-preview016.2"
}
```

## Questions

Is it really a photon error or it comes from my resolver ?
(I'm not sure at all about the ``child: {create: { [...] } }`` to add comment to collection)

Error could comes from the ``@relation`` decorator ?

Thanks a lot.

**Comment by pantharshit00** [comment] 2019-11-18 10:06
I can confirm this as a bug.

I have posted a reproduction here: https://github.com/harshit-test-org/prisma-photonjs-294

**Comment by dpetrick** [comment] 2019-11-22 15:49
Possible duplicate of: https://github.com/prisma/photonjs/issues/297

**Comment by dpetrick** [comment] 2019-12-05 15:48
This will no longer panic in the query engine.

**Closed by dpetrick** 2019-12-05 15:48 UTC
Labels: bug/2-confirmed, kind/bug
