### ISSUE TITLE
Now dev causes: Cannot find module "node_modules/@generated/photon/index.d.ts"

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/photonjs#176] opened 2019-08-05 12:34 UTC
If I deploy my server using `now dev` I receive the following error in console:

```
Cannot find module '/private/var/folders/st/b1sygltj5sg047d6n9d6dx2m0000gn/T/zeit-fun-2db38e526e718/node_modules/@generated/photon/index.d.ts
```

But everything works if I run without `now dev` or even if I use just `now` command.

This is scripts section form my package.json:

```
"scripts": {
    "prepare": "prisma2 generate",
    "start": "ts-node ./src",
    "dev": "now dev"
  }
```

This is my now.json:

```
{
  "version": 2,
  "scope": "***",
  "builds": [
    {
      "src": "src/index.ts",
      "use": "@now/node"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "src/index.ts"
    }
  ]
}
```

I found this folder and indeed, index.d.ts is not there. While index.js is presented.

Is it a known issue or I'm doing something wrong?

**Comment by timsuchanek** [comment] 2019-08-07 14:45
Thanks for reporting @victordombrovskiy!
I tried to reproduce this with exactly the same config and can't reproduce the problem.
Important to note: This is very likely a bug in how `now dev` handles typescript projects, as we just have an ordinary typescript setup.

Can you try it with the latest `prisma2` alpha? In case that doesn't work, you can also `tsc` it yourself with an `outDir` like e.g. `dist` in the `tsconfig.json` and point `now` to the js output file.

I'm closing this here for now as it's not a Photon related issue.
In case it's still an issue for you, you can also create an issue in a zeit/now repo and link it to this one.

**Closed by timsuchanek** 2019-08-07 14:45 UTC
Labels: bug/2-confirmed, release/preview6

**Comment by BjoernRave** [comment] 2019-11-28 12:01
@victordombrovskiy did you manage to find a fix for this?

**Comment by pantharshit00** [comment] 2019-11-28 13:25
@BjoernRave Can you please try this with preview17? This might not be a problem anymore considering facade has been implemented now.

**Comment by BjoernRave** [comment] 2019-11-28 13:58
@pantharshit00 yes, it's happening to me with preview17.1. I have to add though, that same as @victordombrovskiy I am running it inside an `/api` folder in next and only then is it having that problem. 

My scripts: 
```
    "generate": "npm -s run generate:prisma && npm -s run generate:nexus && graphql-codegen --config codegen.yml",
    "generate:prisma": "prisma2 generate",
    "generate:nexus": "NODE_ENV=development ts-node --project tsconfig.prisma.json --transpile-only ./pages/api/src/schema",
```

**Comment by pantharshit00** [comment] 2019-11-28 16:40
I tested out and looks like now is not copying `d.ts` files which nexus is trying to use the generate typings.

It shouldn't be a problem though as nexus will just skip it if it can't find it. You can ignore the error. Can you please please tell me whether you can boot the api using now dev?

**Comment by BjoernRave** [comment] 2019-11-28 16:50
@pantharshit00 yep, everytihng is working fine otherwise :)

**Comment by pantharshit00** [comment] 2019-11-28 17:03
It should now matter anyways because this just happens in dev, it won't happen in now in prod as it doesn't copies dependencies to a temporary location.
