### ISSUE TITLE
Could not retrieve NaiveDateTime from Value in src/libcore/option.rs:1034:5

### ISSUE THREAD

**Issue by rgauny** [prisma/photonjs#189] opened 2019-08-14 01:13 UTC
Error: 
Oops, an unknown error occured! This is on us, you did nothing wrong.
It occured in the `(fieldResolver || defaultFieldResolver)()` invocation in /Users/gaunyr/dev/teams/dtb-portal/backend/node_modules/graphql-extensions/src/index.ts:155:61

  151 // If no resolver has been defined for a field, use the default field resolver
  152 // (which matches the behavior of graphql-js when there is no explicit resolve function defined).
  153 // TODO: Find a way to respect custom field resolvers, see https://github.com/graphql/graphql-js/pull/865
  154 try {
→ 155   const result = (fieldResolver || defaultFieldResolver)(source, args, context, info);

Reason: Could not retrieve NaiveDateTime from Value in src/libcore/option.rs:1034:5

**Comment by pantharshit00** [comment] 2019-08-14 10:31
Hey,

Can you please share a minimal reproduction of the issue with us?

**Comment by rgauny** [comment] 2019-08-14 16:31
model Source {
  id        Int      @id
  createdAt DateTime @map("created_at")
  name      String?
  @@map("sources")
}
const Source = objectType({
  name: "Source",
  definition(t) {
    t.model.id();
    t.model.name();
    t.model.createdAt();
  }
});

**Comment by pantharshit00** [comment] 2019-08-19 17:37
I am unable to reproduce this with `prisma2@2.0.0-preview-7, binary version: 33e5fc84b6bd61602f8d634beb558230ca3e3054`


![image](https://user-images.githubusercontent.com/22195362/63286598-0ab5fe80-c2d6-11e9-836d-8c0656a3a86a.png)

Can you please tell me whether your database is introspected or you are starting from scratch

**Comment by rgauny** [comment] 2019-08-19 18:55
It’s being introspected...I’ll try and get u a trimmed down schema tonight
that shows it isolated

**Comment by janpio** [comment] 2019-09-03 09:10
Reming @rgauny, and have a 🐿 ;)

**Comment by divyenduz** [comment] 2020-01-09 13:37
Closing this as a duplicate of https://github.com/prisma/photonjs/issues/226

If you think that this issue is different, please open a new issue with a minimal reproduction and tag me there.

**Closed by divyenduz** 2020-01-09 13:37 UTC
Labels: bug/0-needs-info, kind/bug
