### ISSUE TITLE
Identity Upsert does not work 

### ISSUE THREAD

**Issue by do4gr** [prisma/photonjs#277] opened 2019-10-29 12:09 UTC
This works: 
![Bildschirmfoto 2019-10-29 um 13 08 02](https://user-images.githubusercontent.com/16278407/67765787-392a2580-fa4d-11e9-9500-526f5c28dd4b.png)
This doesn't: 
![Bildschirmfoto 2019-10-29 um 13 08 10](https://user-images.githubusercontent.com/16278407/67765788-39c2bc00-fa4d-11e9-812f-05d4c9d59b40.png)
![Bildschirmfoto 2019-10-29 um 13 08 23](https://user-images.githubusercontent.com/16278407/67765789-39c2bc00-fa4d-11e9-8c77-bb0f5ef7b820.png)

**Comment by pantharshit00** [comment] 2019-10-31 16:31
Can you please share your datamodel :)

**Comment by divyenduz** [comment] 2020-01-09 10:55
https://github.com/divyendu-test/photonjs-277

I could not reproduce this, tried some variations of the original issue. 

@do4gr I will DM you to get more context, closing this for now.

**Closed by divyenduz** 2020-01-09 10:55 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by divyenduz** [comment] 2020-01-10 16:54
@do4gr confirmed that the new repo looks good
