### ISSUE TITLE
Introspecting fails

### ISSUE THREAD

**Issue by benmb97** [prisma/photonjs#268] opened 2019-10-24 13:20 UTC
Platform:
MacOS: 10.14.6
Node: v12.2.0
npm: v6.9.0
Prisma2: prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe

The introspecting process of the database fails for me.
I followed this guide (https://github.com/prisma/prisma2/blob/master/docs/photon/use-only-photon.md) on how to setup photon for my database.

1. Select Blank project
2. Select MySQL
3. Enter db credentials incuding Database
4. Press Connect

```
⠙ Introspecting MySQL schema  with 49  tables.
 ERROR  Introspection failed:
Cannot read property 'substring' of undefined
```

I then tried the same steps but without selecting database in credential screen and when I selected 'Use existing MySQL database' I received the following error.

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Step4SelectDatabase`. See https://fb.me/react-warning-keys for more information.
    in Unknown (created by Step4SelectDatabase)
    in Step4SelectDatabase
    in Unknown
    in Unknown
    in TabIndexProvider
    in div (created by Box)
    in Box
    in Unknown
    in App
The above error occurred in one of your React components:
    in Unknown (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by BorderBox)
    in div (created by Box)
    in Box (created by BorderBox)
    in BorderBox (created by Step4SelectDatabase)
    in div (created by Box)
    in Box (created by Step4SelectDatabase)
    in Step4SelectDatabase
    in Unknown
    in Unknown
    in TabIndexProvider
    in div (created by Box)
    in Box
    in Unknown
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
```

The issue still occurrs when using Node v10.15.2.

**Comment by pantharshit00** [comment] 2019-10-31 16:49
Hi,

Thanks for reporting this but this has been already reported once. So I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/516

**Closed by pantharshit00** 2019-10-31 16:49 UTC
