### ISSUE TITLE
Self-relations are not working as expected.

### ISSUE THREAD

**Issue by LydiaF** [prisma/photonjs#364] opened 2019-12-24 12:48 UTC
Hi there, 

I apologise in advance if this is my fault :)

My model has these self-relations
```
displacedBy WorksheetState?   @relation(name: "WorksheetStateDisplacementRelation")
displaces   WorksheetState?   @relation(name: "WorksheetStateDisplacementRelation")
```

When I run this code...
```js
await photon.worksheetStates.update({
    where: {id: oldStateId},
    data: {displaces: {connect: {id: displacer.id}},}
  })
```
I get this in the db: 
![image](https://user-images.githubusercontent.com/10000865/71413456-2cd7d880-264a-11ea-9192-a8ddc45e7112.png)

As you can see, the value goes into the displacedBy column. I was expecting it to go into a "displaces" column... but there is no such displaces column so I feel like I am missing something! I am also getting the same error with this code...

```js
const displacer = await photon.${resource}States.create({
    data: {
      ...
      displaces: {connect: {id: oldState.id}}
   }
}
```

In this case, this new entity, `displacer`, gets a value in the "displacedBy" column, whereas what is essentially "meant" is for the `oldState` model to get `displacer.id` in `displacedBy`.

Thank you for any guidance if this is my fault, and if it isn't, thank you for looking into this!

**Comment by LydiaF** [comment] 2019-12-24 13:16
I am also struggling with a very basic query...

![image](https://user-images.githubusercontent.com/10000865/71414465-023c4e80-264f-11ea-8299-a1ca6fa1095d.png)

![image](https://user-images.githubusercontent.com/10000865/71414482-11bb9780-264f-11ea-93be-580a0bd7e6da.png)

![image](https://user-images.githubusercontent.com/10000865/71414544-5e06d780-264f-11ea-91ba-bb37ff06c5ad.png)

The entities that are returned include something that has a not null value for displaced, and excludes something that has a null value for displaced. 

Thank you :)

**Comment by pantharshit00** [comment] 2019-12-27 13:34
Can you please share the whole datamodel or at least the `WorksheetState` model? That would we awesome.

**Comment by LydiaF** [comment] 2019-12-28 17:45
Hey, thank you for looking into this, here it is:
```
model WorksheetState {
  id     String @id @default(cuid())
  platonic WorksheetPlatonic @relation(name: "PlatonicStateWorksheet")
  createdAt DateTime
  createdBy UserPlatonic @relation(name: "WorksheetStateCreatedBy")
  validFrom DateTime
  validUntil DateTime?
  displacedBy WorksheetState? @relation(name: "WorksheetStateDisplacementRelation")
  displaces WorksheetState? @relation(name: "WorksheetStateDisplacementRelation")
  title String
}
```

**Comment by pantharshit00** [comment] 2020-01-06 12:52
Hi,

I think this is just misconception in data modelling. You need two separate relations with four field out of which two will be used as a back relation by the engine.

Use the following datamodel for you use case:
```prisma
model WorksheetState {
  id     String @id @default(cuid())
  platonic WorksheetPlatonic @relation(name: "PlatonicStateWorksheet")
  createdAt DateTime
  createdBy UserPlatonic @relation(name: "WorksheetStateCreatedBy")
  validFrom DateTime
  validUntil DateTime?
  displacedBy WorksheetState? @relation(name: "WorksheetStateDisplacementByRelation")
   displacedByBack WorksheetState? @relation(name: "WorksheetStateDisplacementByRelation")
  displaces WorksheetState? @relation(name: "WorksheetStateDisplacementRelation")
  title String
  displacesBack WorksheetState? @relation(name: "WorksheetStateDisplacementRelation")
  title String
}
```

Now this will create the required columns in the database:
![image](https://user-images.githubusercontent.com/22195362/71819277-6b8d7a00-30b1-11ea-84b0-4460f4b0686d.png)

**Comment by divyenduz** [comment] 2020-01-14 17:49
I am assuming that Harshit's answer addresses this question and closing this one. If that is not the case, please comment on this issue and tag me. 

Thanks

**Closed by divyenduz** 2020-01-14 17:49 UTC
Labels: kind/question

**Comment by stephensamra** [comment] 2020-01-14 20:38
@divyenduz I'm seeing some unexpected behaviour when using self relations.

Given this schema:
```
model Person {
  id     String  @id @default(cuid())
  parent Person? @relation(name: "ParentChildRelation")
}
```

When I create 2 people: parent and child:
```js
    const parent = await photon.people.create({
        data: {
          id: 'parent'
        }
      })

      const child = await photon.people.create({
        data: {
          id: 'child'
        }
      })
```

Then, update the child to have parent as its parent:
```js
    await photon.people.update({
        where: {
          id: 'child'
        },
        data: {
          parent: {
            connect: {
              id: 'parent'
            }
          }
        }
      })
```

This is what I get:
![image](https://user-images.githubusercontent.com/8583469/72380499-71b4d380-370d-11ea-9689-0a3d2b45968f.png)

I would have assumed that the row with the id of child to have `parent` in its parent column. Instead, it's the other way around. Is this supposed to be how this works?

Thanks

**Comment by divyenduz** [comment] 2020-01-15 09:34
@stephensamra This looks like a bug, can you please create a new issue with a small reproduction?

**Comment by stephensamra** [comment] 2020-01-16 19:46
@divyenduz I opened https://github.com/prisma/photonjs/issues/413
