### ISSUE TITLE
ENOENT Error: Error in lift engine: [ Windows OS]

### ISSUE THREAD

**Issue by venkatamandala** [prisma/photonjs#55] opened 2019-06-23 02:25 UTC
Execution of below command or any Lift related command is giving error in Windows (happening for most of the examples provided) No other logs provided except the below error message. Please help ! 

Command> prisma2 lift save --name 'init'
Error Message: ENOENT Error: Error in lift engine:

**Comment by venkatamandala** [comment] 2019-06-23 05:14
More Details about the error, The error is reffering to the Migration-engine line/file as shown below

![image](https://user-images.githubusercontent.com/37226072/59971980-a4b63080-954b-11e9-83e0-2e44c059f2da.png)

[migration-engine] error: Error: spawn C:\Users\<user>\AppData\Roaming\npm\node_modules\prisma2\migration-engine ENOENT
Error: Error in lift engine:

**Comment by Julianojc** [comment] 2019-06-26 14:03
I have the same problem on windows.
```
C:\Users<user>\AppData\Roaming\npm\node_modules\prisma2\migration-engine ENOENT
Error: Error in lift engine
```

**Comment by matthewmueller** [comment] 2019-06-26 15:00
Duplicate of #43

**Closed** 2019-06-26 15:01 UTC
Labels: duplicate
