### ISSUE TITLE
Unable to connect a required 1:m node

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/photonjs#138] opened 2019-07-18 06:40 UTC
Using the following data model:

```
type ID = String @default(cuid()) @id @unique

model Category {
  id                    ID
  types                 Type[]
}

model Type {
  id                    ID
  category              Category
}
```

The following request fails:

```
photon.types.create({
  data: {
    value,
    category: {
      connect: {
        id
      }
    }
  }
})
```

with the following error:

```
ConnectorError(NullConstraintViolation { field_name: "Type.category" })
```

but if I make Type.category nullable, like shown bellow, the request works:

```
model Type {
  id                    ID
  category              Category?
}
```

**Comment by pantharshit00** [comment] 2019-07-18 13:17
Closing as a duplicate of https://github.com/prisma/prisma2/issues/166

**Closed by pantharshit00** 2019-07-18 13:17 UTC
