### ISSUE TITLE
Second default(now()) doesn't work

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/photonjs#183] opened 2019-08-11 03:47 UTC
If `default(now())` is used more that once in a model, it doesn't work:

```
model Email {
  creationMoment                DateTime    @default(now())
  id                            ID
  confirmationExpirationMoment  DateTime    @default(now())
}
```
`confirmationExpirationMoment` doesn't have default value and the following error occurs:

```
Error in connector: Error querying the database: MySqlError { ERROR 1364 (HY000): Field 'confirmationExpirationMoment' doesn't have a default value }
```

**Comment by timsuchanek** [comment] 2019-08-15 15:58
@mavilein confirms that this is reproducible, but relates to a bigger work item related to the expression system, which needs to be implemented first.

**Comment by divyenduz** [comment] 2020-01-09 11:35
Internal note: This is a lift issue, introspection does not produce `@defaut(now())` afaik. I tried it on a DB and this was the result, since `now()` is a Prisma schema function concept, it is not reflected in the database. 

![image](https://user-images.githubusercontent.com/746482/72064544-63655280-32dc-11ea-9549-5db1baa95568.png)

**Comment by mavilein** [comment] 2020-01-09 13:01
This is not a lift but a query engine issue. We are free to decide whether we implement `now()` through a db level concept or simply do in the query engine. We decided to do it in the query engine.

**Comment by mavilein** [comment] 2020-01-10 08:55
This should be fixed now. Please retest this.

**Comment by divyenduz** [comment] 2020-01-10 14:31
This is not reproducible anymore.

**Closed by divyenduz** 2020-01-10 14:31 UTC
Labels: bug/2-confirmed, kind/bug
