### ISSUE TITLE
IoError in Serverless Function

### ISSUE THREAD

**Issue by dlehmhus** [prisma/photonjs#263] opened 2019-10-20 16:07 UTC
I'm trying to run photon in an AWS Servereless Function (zeit now) against a MySQL database. After a couple of invocations I get the following error: 
```
Error in Photon: 
Error: Reason: Error in connector: Error querying the database: IoError { failed to fill whole buffer } 
at NodeEngine.handleErrors (/foo/node_modules/@generated/photon/runtime/index.js:13236:15)
at currentRequestPromise.then (/foo/node_modules/@generated/photon/runtime/index.js:13196:29)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
```

 I'm using **prisma2@2.0.0-preview014.2**

**Comment by pantharshit00** [comment] 2019-10-22 06:25
Can you please share the actual function code and your schema?

**Comment by dlehmhus** [comment] 2019-10-23 19:09
@pantharshit00 Here you can see the actual [function code](https://github.com/dlehmhus/prisma-demo). It is basically this [GraphQL Server with Authentication & Permissions](https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql-auth) example. 
I also have to correct my bug report above, it doesn't need "a couple of invocations", a single request to the function and a couple of minutes idle time is enough the get this error.

**Comment by pantharshit00** [comment] 2019-10-28 15:06
I am still unable to reproduce this and the example code doesn't export any lambda functions.

Can you please share a complete reproduction?

**Comment by divyenduz** [comment] 2020-01-09 11:01
@dlehmhus I am using Photon in lambda and with Zeit for some projects and I did not run into this. 

I am closing this issue as it is old and lacks information. If you think that this is still an issue, please create a new issue with a small reproduction and tag me there 🙏

**Closed by divyenduz** 2020-01-09 11:01 UTC
Labels: bug/0-needs-info, kind/bug
