### ISSUE TITLE
findOne returns Error when no record was found.

### ISSUE THREAD

**Issue by reinvanimschoot** [prisma/photonjs#98] opened 2019-07-04 06:36 UTC
Yesterday I noticed the following bug:

`let user = await context.photon.users.findOne({ where: { email: args.email } });`

When the `findOne` function cannot find a record, it doesn't return null, which I believe would be the expected behaviour but instead it returns an error:

<img width="358" alt="Screenshot 2019-07-04 at 08 35 25" src="https://user-images.githubusercontent.com/35171567/60644539-bdb9be00-9e36-11e9-9733-bbd81c2e8826.png">

**Comment by schickling** [comment] 2019-07-04 14:50
This is a duplicate of #89

**Closed by schickling** 2019-07-04 14:50 UTC
