### ISSUE TITLE
Unreadable error trace message

### ISSUE THREAD

**Issue by soqt** [prisma/photonjs#367] opened 2019-12-26 09:27 UTC
I got a "INTERNAL_SERVER_ERROR" and the `stacktrace` is totally unreadable, it looks something like this:
<img width="653" alt="Screen Shot 2019-12-26 at 5 25 19 PM" src="https://user-images.githubusercontent.com/10392539/71469621-bcc18200-2804-11ea-9431-66685f7dff79.png">

prisma/photon: 2.0.0-preview018.2
nexus: ^0.12.0-rc.5
nexus-prisma: ^0.6.1

**Comment by pantharshit00** [comment] 2019-12-27 13:59
Stacktrace is shown in your cli with proper formatting(it is the interactive error that we create).

But I do think we should strip the ANSI characters in the error object that we throw to the user.

**Comment by janpio** [comment] 2019-12-27 18:28
Unreadable error message definitely is a bug. (Possibly even a regression because of the implementation of the error spec.)

**Comment by soqt** [comment] 2019-12-30 02:36
It seems happen if I didn't `lift up` new data models.

**Comment by divyenduz** [comment] 2020-01-06 13:24
Closing this as a duplicate of https://github.com/prisma/photonjs/issues/195

It was never implemented, I am adding a candidate label to this so it is (hopefully) picked up by us soon 🙏 

This workaround might work for you, if the error throwing logic is in your application or you can modify that in your server library: https://github.com/prisma/photonjs/issues/195#issuecomment-535909631

**Comment by divyenduz** [comment] 2020-01-06 13:25
@soqt From your last comment, it looks like this was fixed for you anyways? Is that correct?

**Closed by divyenduz** 2020-01-06 13:24 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate
