### ISSUE TITLE
Unable to apply 'where' arguments beyond (3rd?) level

### ISSUE THREAD

**Issue by artemzakharov** [prisma/photonjs#322] opened 2019-12-09 08:03 UTC
I have a pretty simple find operation that looks like this:

```
const foos = await photon.foo.findMany({
  where: {
    a: {
      some: {
        b: {
          some: {
            c: {
              d: {
                id: ''
              }
            }
          }
        }
      }
    }
  },
  data: {
    ...
  }
})
```
When I run this query, it throws this error (with a long stack trace afterwards):
```
Reason: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P01"), message: "missing FROM-clause entry for table \"j1\"", detail: None, hint: None, position: Some(Original(423)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(3140), routine: Some("errorMissingRTE") }) }
```
If I remove the **d** block from the **where** clause, the error goes away. In addition, the actual query inside the block appears to be irrelevant; if I move it to one of the higher levels (where it's still valid for those types, like with the simple check of the ID being equal to something), the error also goes away.

Also, for clarification, the relations in the schema are as follows:
**Foo** to **A**: One-to-many
**A** to **B**: One-to-many
**B** to **C**: One-to-one
**C** to **D**: Many-to-one

My version of prisma is `preview018`, and my database type is Postgres.

**Comment by pantharshit00** [comment] 2019-12-11 19:14
I am unable to reproduce this:
![image](https://user-images.githubusercontent.com/22195362/70652317-6850cb00-1c78-11ea-98ba-b691d1ca85ac.png)


I am using the following schema for reproduction:
```prisma
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://xxxx:xxxxx@localhost:5432/issue_photon_322?schema=public"
}

model Foo {
  id String @id @default(cuid())
  a  A[]
}

model A {
  id   String  @id @default(cuid())
  name String?
  b    B[]
}

model B {
  id String @id @default(cuid())
  c  C
}

model C {
  id String @id @default(cuid())
  d  D
}

model D {
  id String @id @default(cuid())
  c  C[]
}
```

Can you please share the exact datamodel that you are using? Also, try this again with 18.1 once.

**Comment by artemzakharov** [comment] 2019-12-11 20:53
Still happens with `18.1`. Can you add `@relation` names to your relations, as well as some mock data to the DB and try again? 

If that doesn't work, I could perhaps share the schema in a more private channel, I just don't want to post it here because it's part of a closed-source project.

**Comment by janpio** [comment] 2019-12-11 21:53
As @pantharshit00 will not be here in the next days, his colleague @divyenduz will take over. You can send him the schema to singh@prisma.io (If you need an NDA before you can do that, we can accommodate that as well of course - just let Divy know) <3

**Comment by artemzakharov** [comment] 2019-12-12 01:05
Okay, having taken another look at my code, I've identified a critical part that I missed when creating my original bug report - **I also had other filters on the C level of the find call:**

```
const foos = await photon.foos.findMany({
  where: {
    a: {
      some: {
        b: {
          some: {
            c: {
              v1: {              <--
                lt: 0            <--
              },                 <--
              v2: false,         <--
              v3: true,          <--
              d: {
                id: {
                  not: ''
                }
              }
            }
          }
        }
      }
    }
  }
});
```

Here is an updated schema to reflect this:

```
model Foo {
  id String @id @default(cuid())
  a  A[]
}

model A {
  id   String  @id @default(cuid())
  name String?
  b    B[]
}

model B {
  id String @id @default(cuid())
  c  C
}

model C {
  id String  @id @default(cuid())
  d  D
  v1 Int
  v2 Boolean
  v3 Boolean
}

model D {
  id String @id @default(cuid())
  c  C[]
}
```



Playing around with this, I'm able to replicate the issue by having both the checks on **v1**, **v2**, and **v3**, and the check on **d** active at the same time. If I remove either the entire group of the first 3, or the check on **d**, however, the issue disappears:

```
c: {
  v1: {
    lt: 0
  },
  v2: false,
  v3: true
}
```
```
c: {
  d: {
    id: {
      not: ''
    }
  }
}
```
Both of the above run successfully - only the combination appears to cause the bug. 

It also does not look like any data in the DB is needed - I was able to replicate the issue with an empty one.

**Comment by pantharshit00** [comment] 2019-12-18 19:24
Thanks, I was able to reproduce this now. 

I have posted a ready to go reprodution here: https://github.com/harshit-test-org/prisma-photonjs-322

**Comment by tomhoule** [comment] 2020-01-10 13:53
I checked with the query engine on `master` and I am practically sure it was fixed by the PR in https://github.com/prisma/photonjs/issues/356

I will still wait until I can confirm this on an alpha release before closing.

**Comment by tomhoule** [comment] 2020-01-15 13:40
I can confirm the bug repro @pantharshit00 posted above does not crash anymore with `prisma2@2.0.0-alpha.538`. A preview release is also coming soon.

**Closed by tomhoule** 2020-01-15 13:40 UTC
Labels: bug/2-confirmed, kind/bug
