### ISSUE TITLE
Subscriptions do not work yet

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/photonjs#197] opened 2019-08-20 16:55 UTC
I got to know in Slack, subscriptions aren't implemented yet in Prisma2.

I didn't found any issues so I wasted an entire day [asking questions](https://stackoverflow.com/q/57577464/6141587) so opening this to track Subscriptions.

I guess I should've read [Limitations.md](https://github.com/prisma/prisma2/blob/master/docs/limitations.md) but searching issues was the 1st thing on my mind.

**Comment by pantharshit00** [comment] 2019-08-21 12:26
Closing as duplicate of https://github.com/prisma/prisma2/issues/298

I am sorry that you had this trouble. As mentioned in the above issue we will bring back subscriptions using an events engine.

**Closed by pantharshit00** 2019-08-21 12:26 UTC
