### ISSUE TITLE
UniqueConstraintViolation on newly created database

### ISSUE THREAD

**Issue by chrisui** [prisma/photonjs#171] opened 2019-08-02 20:41 UTC
I'm seeing the following "duplicate key" violation when trying to do a simple insert on my `lift` created database tables.

```
db_1     | 2019-08-02 20:31:29.980 UTC [28] ERROR:  duplicate key value violates unique constraint "Thread_pkey"
db_1     | 2019-08-02 20:31:29.980 UTC [28] DETAIL:  Key (id)=(0) already exists.
db_1     | 2019-08-02 20:31:29.980 UTC [28] STATEMENT:  INSERT INTO "public"."Thread" ("createdAt", "updatedAt", "name") VALUES ($1, $2, $3) RETURNING "public"."Thread"."id"
```

My model looks like this:

```
datasource pg {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator photonjs {
  provider = "photonjs"
  output   = "node_modules/@generated/photon"
}

model User {
  id          Int       @id
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  email       String    @unique
  name        String?
  threads     Thread[]
}

model Thread {
  id          Int       @id
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  name        String?
  people      User[]
}
```

My seed code I'm running (triggering the violation, after a initial `lift save` and then `lift up`) looks like this:

```
import Photon from '@generated/photon';

async function main() {
    const p = new Photon();
    console.log("Connecting");
    await p.connect();
    console.log("Seeding");
    await p.users.create({
        data: {
            email: 'chris@example.com',
            name: 'Chris',
            threads: {
                create: [
                    {name: "Example Thread"},
                    {name: "Example Thread 2"}
                ]
            }
        }
    });
    console.log("Seeded");
    await p.disconnect();
}

main().catch(console.error).then(() => process.exit());
```

It seems something is messing up the primary sequence within the database setup but I'm unsure what?

### Update 1

Rolling back to the beginning I notice an error when running `prisma2 lift save`.

```
db_1     | 2019-08-02 20:51:49.115 UTC [73] ERROR:  relation "_Migration" already exists
db_1     | 2019-08-02 20:51:49.115 UTC [73] STATEMENT:  CREATE TABLE "public"."_Migration" ("revision" SERIAL PRIMARY KEY NOT NULL, "name" TEXT NOT NULL, "datamodel" TEXT NOT NULL, "status" TEXT NOT NULL, "applied" INTEGER NOT NULL, "rolled_back" INTEGER NOT NULL, "datamodel_steps" TEXT NOT NULL, "database_migration" TEXT NOT NULL, "errors" TEXT NOT NULL, "started_at" timestamp(3) NOT NULL, "finished_at" timestamp(3));
```

Wasn't aware `save` was supposed to update the db. Regardless seems to be trying to create the table twice even?

Then when I run `prisma2 lift up` for the initial table creations (first, single migration) it spits out loads more "_Migration table already exists" errors.

```
db_1     | 2019-08-02 20:53:41.525 UTC [83] ERROR:  relation "_Migration" already exists
db_1     | 2019-08-02 20:53:41.525 UTC [83] STATEMENT:  CREATE TABLE "public"."_Migration" ("revision" SERIAL PRIMARY KEY NOT NULL, "name" TEXT NOT NULL, "datamodel" TEXT NOT NULL, "status" TEXT NOT NULL, "applied" INTEGER NOT NULL, "rolled_back" INTEGER NOT NULL, "datamodel_steps" TEXT NOT NULL, "database_migration" TEXT NOT NULL, "errors" TEXT NOT NULL, "started_at" timestamp(3) NOT NULL, "finished_at" timestamp(3));
db_1     | 2019-08-02 20:53:41.589 UTC [87] LOG:  could not receive data from client: Connection reset by peer
db_1     | 2019-08-02 20:53:41.620 UTC [89] ERROR:  relation "_Migration" already exists
db_1     | 2019-08-02 20:53:41.620 UTC [89] STATEMENT:  CREATE TABLE "public"."_Migration" ("revision" SERIAL PRIMARY KEY NOT NULL, "name" TEXT NOT NULL, "datamodel" TEXT NOT NULL, "status" TEXT NOT NULL, "applied" INTEGER NOT NULL, "rolled_back" INTEGER NOT NULL, "datamodel_steps" TEXT NOT NULL, "database_migration" TEXT NOT NULL, "errors" TEXT NOT NULL, "started_at" timestamp(3) NOT NULL, "finished_at" timestamp(3));
db_1     | 2019-08-02 20:53:41.699 UTC [93] ERROR:  relation "_Migration" already exists
db_1     | 2019-08-02 20:53:41.699 UTC [93] STATEMENT:  CREATE TABLE "public"."_Migration" ("revision" SERIAL PRIMARY KEY NOT NULL, "name" TEXT NOT NULL, "datamodel" TEXT NOT NULL, "status" TEXT NOT NULL, "applied" INTEGER NOT NULL, "rolled_back" INTEGER NOT NULL, "datamodel_steps" TEXT NOT NULL, "database_migration" TEXT NOT NULL, "errors" TEXT NOT NULL, "started_at" timestamp(3) NOT NULL, "finished_at" timestamp(3));
db_1     | 2019-08-02 20:53:41.954 UTC [101] ERROR:  relation "_Migration" already exists
db_1     | 2019-08-02 20:53:41.954 UTC [101] STATEMENT:  CREATE TABLE "public"."_Migration" ("revision" SERIAL PRIMARY KEY NOT NULL, "name" TEXT NOT NULL, "datamodel" TEXT NOT NULL, "status" TEXT NOT NULL, "applied" INTEGER NOT NULL, "rolled_back" INTEGER NOT NULL, "datamodel_steps" TEXT NOT NULL, "database_migration" TEXT NOT NULL, "errors" TEXT NOT NULL, "started_at" timestamp(3) NOT NULL, "finished_at" timestamp(3));
db_1     | 2019-08-02 20:53:41.979 UTC [103] LOG:  could not receive data from client: Connection reset by peer
```

at a glance though it seems everything has been setup appropriately?

![Capture](https://user-images.githubusercontent.com/1042432/62398329-4def3e00-b570-11e9-95e3-6e3f97c2a8fe.PNG)

I then run my original seeding script and get the originally reported error with the unique violation on primary key.

```
db_1     | 2019-08-02 20:56:19.098 UTC [110] ERROR:  duplicate key value violates unique constraint "Thread_pkey"
db_1     | 2019-08-02 20:56:19.098 UTC [110] DETAIL:  Key (id)=(0) already exists.
db_1     | 2019-08-02 20:56:19.098 UTC [110] STATEMENT:  INSERT INTO "public"."Thread" ("createdAt", 
"updatedAt", "name") VALUES ($1, $2, $3) RETURNING "public"."Thread"."id"
```

For extra info I'm running all of this within a `node:12` image based docker container with the following prisma2 version.

```
$ docker-compose exec api ./node_modules/.bin/prisma2 --version
prisma2@2.0.0-preview-3.2, binary version: acd6dd8dcf027b84a94af26b36ded779f1f56b1d
```

**Comment by pantharshit00** [comment] 2019-08-05 18:39
What `prisma2 lift save` does is to create that _Migrations folder and it will store all of the migration from the "migrations" folder in your database. `prisma2 lift up` does is to apply those migrations.

Another part of the issue is reported in #33. But I think we can keep this issue as well as this one is related to many-to-many relations. I can confirm that.

**Comment by chrisui** [comment] 2019-08-05 18:46
👍 Cheers for the confirmation. Any suggestion as to how to workaround temporarily?

**Comment by pantharshit00** [comment] 2019-08-05 19:29
This is a big issue involving internals of the query engine. It will need some to get fixed as we are rewriting some parts of the engine

**Comment by chrisui** [comment] 2019-08-05 20:17
Ok. Just to clarify you're saying that many-to-many relationships (as [documented](https://github.com/prisma/prisma2/blob/master/docs/relations.md) are currently fundamentally broken and I should really be looking at an alternative to prisma right now?

Absolutely fine if that's the case I just want to make sure there is no workaround. :)

**Comment by pantharshit00** [comment] 2019-08-05 20:43
Oh sorry, I mistook this issue for another bug 🤦‍♂.

This issue is a duplicate of https://github.com/prisma/prisma2/issues/135, easily fixable.

Just use String IDs for now:
```groovy
model User {
  id String @id @default(cuid())
  email     String   @unique
  name      String?
  threads   Thread[]
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Thread {
  id        String   @id @default(cuid())
  name      String?
  people    User[]
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```
This datamodel is working perfectly.

![image](https://user-images.githubusercontent.com/22195362/62493798-a2542100-b7ef-11e9-8e8b-c711e3baed12.png)
![image](https://user-images.githubusercontent.com/22195362/62493820-aed87980-b7ef-11e9-82d5-ffd754c5aa4a.png)
![image](https://user-images.githubusercontent.com/22195362/62493832-b39d2d80-b7ef-11e9-8ca1-106b0334d3c6.png)


You might need to start fresh considering you need to change the type of Primary key.

**Comment by chrisui** [comment] 2019-08-06 18:45
Hey @pantharshit00 I've tried with the above and while a little further I'm getting the following error:

```
Error: Error in Photon:
ConnectorError(NullConstraintViolation { field_name: "User.null, 2019-08-06 18:44:11.903, 2019-08-06 18:44:11.903, chris@getfabric.app, Chris)." })      
    at PhotonFetcher.<anonymous> (/usr/src/app/node_modules/@generated/photon/index.js:34:23)
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/node_modules/@generated/photon/index.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Note I've tested this on my previous version and the new release.

```
$ docker-compose run api ./node_modules/.bin/prisma2 --version
prisma2@2.0.0-preview-5, binary version: 29f6d9f7f6d0a85cc30df1809733612bab56a1c5
```

**Comment by chrisui** [comment] 2019-08-06 18:47
Looks like default cuid is not being generated/passed through?

**Comment by chrisui** [comment] 2019-08-06 19:16
Have pulled everything down, forced a container rebuild and tried again. Looks healthy now - thank you!

I have a suggestion to help the debug experience. https://github.com/prisma/prisma2/issues/334

**Closed** 2019-08-07 04:57 UTC
Labels: bug/1-repro-available, kind/bug
