### ISSUE TITLE
Sorting is case sensitive

### ISSUE THREAD

**Issue by nhuesmann** [prisma/photonjs#327] opened 2019-12-12 17:42 UTC
### To Reproduce
1. Make sure you're running latest version of `prisma2`. I'm on `prisma2@2.0.0-preview018.2, binary version: 3c4da1d6caa0c40a0210a346ec982c77f74e18c7`
2. `prisma2 init`, choose Starter Kit, Typescript, GraphQL api, SQLite
3. Modify `schema.ts` by exposing the following basic query:
```
t.crud.posts({
  alias: 'posts',
  filtering: true,
  ordering: true,
  pagination: true,
});
```
4. Create a new post with the title `"a new post"`. MUST BE LOWERCASE.
5. Run the posts query as follows:
```
query POSTS {
  posts(orderBy: { title: asc }) {
    title
  }
}
```
6. Observe that "a new post" is last in the list, when it should be first.

I feel that sorting should be case insensitive. Is there something I'm missing in the current functionality that allows this option?

**Comment by pantharshit00** [comment] 2019-12-18 19:28
This is kinda expected behaviour as we currently don't support case insensitive queries in the photon level. 

So I will close this as a duplicate of https://github.com/prisma/photonjs/issues/343

**Closed by pantharshit00** 2019-12-18 19:28 UTC
