### ISSUE TITLE
UniqueInput type has id field only

### ISSUE THREAD

**Issue by vadim-shilov** [prisma/photonjs#306] opened 2019-11-21 16:57 UTC
Hello!

There is a model:
```
model Profile {
  id String @id @default(cuid())
  profileType ProfileType @map(name: "profile_type_id")
  profileId String @map(name: "profile_id")
  user User
  @@map(name: "profiles")
  @@unique([profileType, profileId])
}
```

After I run the commands `prisma2 generate && prisma2 lift up` a created table in the DB has a unique constraint for 2 fields. But a generated type has `id` field only :(
```
export declare type ProfileWhereUniqueInput = {
    id?: string | null;
};
```
What do you think about this option?
```
where: ProfileWhereUniqueInput;

declare type ProfileWhereUniqueInput = {
    id?: string | null;
    profileTypeProfileId? ProfileTypeProfileIdUnique | null;
};

declare type ProfileTypeProfileIdUnique = {
    profileType: string | null;
    profileId:: string | null;
};
```

**Comment by pantharshit00** [comment] 2019-11-22 09:10
Hello

The `@@unique` directive is not implemented yet. Schema parser is able to parse it but it is ignored by the backend right now. So please add `@unique` to fields right now that you want to be unique or wait until this part is implemented.


I am going to close this as a duplicate of https://github.com/prisma/prisma-engine/issues/28

**Closed by pantharshit00** 2019-11-22 09:10 UTC

**Comment by julien1619** [comment] 2020-02-26 17:12
I think that `@@unique` is implemented and it works but only with scalar fields, but it does not fully cover what this issue is about.

When I use a relation as an `@id` or inside a `@@unique` as specified in these tests https://github.com/prisma/prisma-engines/commit/4108df5e6a678c1dc8637a9ae40e886064789d39 the generated code does not contain the relation fields in `WhereUniqueInput`, only scalar fields are present.

Is it a bug or is it only supported by the engine but not in the generated code?

Example:

**schema.prisma**

```
model Company {
  id   String @default(uuid()) @id
  name String
}

model Subside {
  id        String  @default(uuid()) @id
  company   Company @relation(references: [id])
  reference String

  @@unique([company, reference])
}
```

**Generated code**
```
export type ReferenceCompoundUniqueInput = {
  reference: string
}

export type SubsideWhereUniqueInput = {
  id?: string | null
  company_reference?: ReferenceCompoundUniqueInput | null
}
```

**Comment by janpio** [comment] 2020-02-26 17:54
Please open a new issue @julien1619 and we will look into this.
