### ISSUE TITLE
Large Payloads

### ISSUE THREAD

**Issue by aarshaw** [prisma/photonjs#246] opened 2019-10-06 09:02 UTC
Hi, I'm attempting to post quite a lot of data at the one time to a Postgres db via prisma2.

Trying to deduce the source of the following error:

```
{
  "statusCode": 413,
  "statusMessage": "Payload Too Large",
}
```

Is this limit configurable anywhere? - and where is it coming from - the payload itself is GraphQL - so I'm assuming somewhere in the query engine - but why is an HTTP request being made with a GraphQL body - I was under the impression this was all done locally?

**Comment by janpio** [comment] 2019-10-07 13:56
I transferred this into the `photonjs` repo as this is about using Photon.

**Comment by aarshaw** [comment] 2019-10-09 05:11
@janpio I think the source of this issue is definitely in the query-engine - the max payload size tends to be an issue that stems from the server.

Have done a bit of digging and looks like the max payload size ~> from what I can tell the [server](https://github.com/prisma/prisma-engine/blob/master/query-engine/prisma/src/server.rs) (I don't speak rust) can take 32kb by default... this looks to be configurable using [JsonConfig](https://docs.rs/actix-web/1.0.0-rc/actix_web/web/struct.JsonConfig.html) and increasing the max body size

I really do think this is worth doing as the GraphQL requests can get quite large given the amount of whitespace they contain and mine is probably going to be a fairly common use case

**Comment by xero0001** [comment] 2019-10-21 21:40
I'm also having this large payload issue. The error message is exactly same with my case.

[https://github.com/prisma/prisma2/issues/771](https://github.com/prisma/prisma2/issues/771)

I'm building online text editor and it uploads image which is converted into base64, so text size is little bit large.

But in my case, the error didn't generated when payload size was less than around 200kb(or much larger. I don't know how much it gets larger when PNG is converted into base64. Error started to generate when I contained 200kb image.), which is definitely larger than 32kb. So I'm  wondering if the error is really caused by default 32kb setting.

**Comment by xero0001** [comment] 2019-10-22 22:56
https://github.com/xero0001/prisma2-payloaderror-reproducer

**Comment by xero0001** [comment] 2019-10-22 23:12
Here's my git repository which can reproduce the error, according to pantharshit00's request at https://github.com/prisma/prisma2/issues/771.

https://github.com/xero0001/prisma2-payloaderror-reproducer

The code is based on "react-graphql-fullstack" example(https://github.com/prisma/prisma-examples/tree/prisma2/misc/react-graphql-fullstack).

I only added "bodyParserOptions" at server side which sets the limitation of body size to 50mb, and there's nothing else I added or modified.

The error is reproducable by,
1. Running client and server
2. Copying the texts of "base64.txt"
3. Press create draft button(on client side)
4. And pasting it multiple times and click the create button.

The size of "base64.txt" is about 50kb and if you paste it 5 or more times in one post you will see the 413 payload too large error.

Thanks to pantharshit00 and I hope this could help!

**Comment by pantharshit00** [comment] 2019-10-25 11:35
I am unable to reproduce this.

![image](https://user-images.githubusercontent.com/22195362/67568308-1dacdb00-f72c-11e9-915d-e2c086cb4af8.png)


Photon handled the base64 text very easily. I used photon version `prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe`

**Comment by xero0001** [comment] 2019-10-26 01:42
Error is produced when "**paste it 5 or more times** in one post".

As I see from your post, I think you paste it just one time.

As English is not my first-hand language, I might have wrote it confusing.

**Comment by xero0001** [comment] 2019-10-26 02:00
I updated my "base64.txt" on github which is five-times-duplicated version of old "base64.txt"

you can just download it from my github repository
https://github.com/xero0001/prisma2-payloaderror-reproducer

And this is the error screenshot captured from safari.
https://github.com/xero0001/prisma2-payloaderror-reproducer/blob/master/error.png

**Comment by pantharshit00** [comment] 2019-10-28 15:12
Ok, I can reproduce this now. 

Thanks for the detailed reproduction. I think we can have an option to increase the max load.

**Comment by xero0001** [comment] 2019-10-29 01:55
It's amazing! Thank you.

**Comment by pimeys** [comment] 2019-10-29 15:28
This has been fixed in my experimental branch already, we tested it with the example given here with @pantharshit00 and the error is gone.

Merging this to master needs first the core refactoring from @dpetrick, which happens today or tomorrow. After that we'll start porting the experimental async/await branch to master, introducing a new web server with higher limits (and in general waaaay faster query engine).

If you want to try it now, you need to compile a bit of rust:
- Clone the `bench` branch from https://github.com/prisma/prisma-engine/tree/bench
- Install [rustup](https://rustup.rs/) and with it install rustc beta:
``` bash
> rustup install beta
> rustup default beta
```
- Compile `query-engine` in release mode:
``` bash
> cargo build --release --bin prisma
```
- The release binary will be in `target/release/prisma`

The binary needs to be copied somewhere in `node_modules`, replacing the existing `query-engine-linux-glibc-libssl1.1.0` or `query-engine-darwin` or whatever binary fits to the current distro.

Or wait until next Monday! :)

**Comment by pimeys** [comment] 2019-11-07 15:50
Fixed on master.

**Closed by pimeys** 2019-11-07 15:50 UTC
Labels: bug/2-confirmed, kind/bug
