### ISSUE TITLE
@id for mysql does not work @preview-6

### ISSUE THREAD

**Issue by mazzaker** [prisma/photonjs#187] opened 2019-08-12 15:08 UTC
first mutation leads to id set to 0, after this no further mutation to this object is possible

```
{
  "data": null,
  "errors": [
    {
      "message": "\n\u001b[31mInvalid \u001b[1m`photon.()`\u001b[22m invocation in \u001b[4m/Users/DC-BT/Documents/Projects/hello-prisma/node_modules/graphql-extensions/src/index.ts:155:61\u001b[24m\u001b[39m\n\n\n\n\u001b[31m\u001b[1mReason: \u001b[22m\u001b[39m\u001b[31mError in connector: Unique constraint failed: User.id\u001b[39m\n\u001b[31m\u001b[39m",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createOneUser"
      ]
    }
  ]
}
```

schema: 
```
datasource db {
  provider = "mysql"
  url      = "mysql://root:@localhost:3306/hello"
  default  = true
}

generator photon {
  provider = "photonjs"
}

generator nexus_prisma {
  provider = "nexus-prisma"
}

model User {
  id    Int    @id
  email String @unique
  name  String
  posts Post[]
}

model Post {
  id        Int      @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(false)
  title     String
  content   String
  author    User
}
```

**Comment by pantharshit00** [comment] 2019-08-13 14:31
Duplicate of https://github.com/prisma/prisma2/issues/135

**Comment by pantharshit00** [comment] 2019-08-13 14:31
Duplicate of https://github.com/prisma/prisma2/issues/135

**Closed by pantharshit00** 2019-08-13 14:31 UTC
