### ISSUE TITLE
Invalid `ctx.photon.posts.create()` invocation 

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [prisma/photonjs#279] opened 2019-10-29 17:40 UTC
HI im using the prisma auth example and i getting this error : 
```
Invalid `ctx.photon.posts.create()` invocation in 
  → 355 return await ctx.photon.posts.create({
      data: {        title: 'jlk'
                       content:"asda",
                realPart: {
                     set: [
                         3,
                        5.5,
                         5.5
                      ]
                ~~~~~~
                },

                        
}
on photon.createOnePost. Provided List<Float | Int>, expected List<Float>.
Argument set: Got invalid value
[
  3,
  5.5,
  5.5
]
```
My Models:

```prisma
generator photon {
  provider = "photonjs"
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean @default(true)
  title     String?
  content   String?
  realPart: Float[]  
}

model User {
  id       String  @default(cuid()) @id
  email    String  @unique
  password String
  name     String?
  posts    Post[]
}
```

Please Help me :D

**Comment by pantharshit00** [comment] 2019-10-31 16:59
Thanks for reporting this!

Looks like a bug to me when you use Floats and Integers at the same time while interesting. Photon should convert those integers in floats. Also, 12.0 is not possible as photon is converting them to integers.

Reproductions for internal use: https://github.com/harshit-test-org/prisma-photonjs-279

**Comment by GolfredoPerezFernandez** [comment] 2019-11-03 16:15
thank you for support. can you let me know when be ready :)

**Comment by pantharshit00** [comment] 2019-11-19 12:59
related: https://github.com/prisma/prisma-engine/issues/160

**Comment by dpetrick** [comment] 2019-11-20 16:50
Fixed in the query engine, waiting for confirmation that this is no longer an issue on the Photon side (with Preview-17).

**Comment by timsuchanek** [comment] 2019-12-10 17:07
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by GolfredoPerezFernandez** [comment] 2019-12-31 22:10
Hello! this is my schema, im using prisma2@alpha version:

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  default  = true
}

generator photon {
  provider = "photonjs"
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean @default(true)
  title     String
  content   String?
  author    User?
  dataType String
  materialType String
  imaginaryPartX Float[]   
  imaginaryPartY Float[]  
  dfImaginaryPartX Float[] 
  dfImaginaryPartY Float[] 
  dfRealPartX Float[]   
  dfRealPartY Float[]  
}

model User {
  id       String  @default(cuid()) @id
  email    String  @unique
  password String
  name     String?
  posts    Post[]
}
and is given me this error:

Field "imaginaryPartX" in model "Post" can't be a list. The current connector does not support lists of primitive types.

**Comment by GolfredoPerezFernandez** [comment] 2020-01-02 05:06
Hello! this is my schema, im using prisma2@alpha version:

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  default  = true
}

generator photon {
  provider = "photonjs"
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean @default(true)
  title     String
  content   String?
  author    User?
  dataType String
  materialType String
  imaginaryPartX Float[]   
  imaginaryPartY Float[]  
  dfImaginaryPartX Float[] 
  dfImaginaryPartY Float[] 
  dfRealPartX Float[]   
  dfRealPartY Float[]  
}

model User {
  id       String  @default(cuid()) @id
  email    String  @unique
  password String
  name     String?
  posts    Post[]
}
and is given me this error:

Field "imaginaryPartX" in model "Post" can't be a list. The current connector does not support lists of primitive types.

**Comment by pantharshit00** [comment] 2020-01-17 13:26
This is not fixed in the `preview019`. Reopening.

**Closed** 2020-01-17 13:38 UTC
Labels: bug/2-confirmed, kind/bug
