### ISSUE TITLE
Photon Zeebe bug (prototype pollution?)

### ISSUE THREAD

**Issue by tvvignesh** [prisma/photonjs#296] opened 2019-11-17 13:28 UTC
Hi. I am using Zeebe (https://zeebe.io/) along with Photon and I am facing an issue when running them together (I guess Photon is polluting the prototype as per the discussion I had with Zeebe community). Zeebe works well without Photon but when the `@generated` files from Photon are imported, Zeebe fails with an error.

To demonstrate this issue, I have created a minimal repo where you can see this: https://github.com/tvvignesh/prisma-zeebe-bug

**Comment by pantharshit00** [comment] 2019-11-18 09:57
I can confirm this bug.

**Comment by divyenduz** [comment] 2019-12-27 08:35
@tvvignesh Do you have a link to your discussion with the zeebe community?

**Comment by tvvignesh** [comment] 2019-12-27 10:24
@divyenduz Sure. Though I am not sure how relevant that would be.

Link to slack thread: https://zeebe-io.slack.com/archives/C6WGNHV2A/p1573742151247900

In case you don't want to join their slack channel, I have put the same in a gist here: https://gist.github.com/tvvignesh/0e095d0005b17faa3e8c2b3442d9fb24

**Comment by divyenduz** [comment] 2019-12-27 11:07
Related issue: https://github.com/creditsenseau/zeebe-client-node-js/issues/106

**Comment by tvvignesh** [comment] 2019-12-27 11:10
> Related issue: [creditsenseau/zeebe-client-node-js#106](https://github.com/creditsenseau/zeebe-client-node-js/issues/106)

The commit made saying the issue was fixed was for something different though. This issue still exists even after the commit.

**Comment by divyenduz** [comment] 2019-12-27 11:19
`static async scanBpmnObjectForTasks(bpmnObject) {`

Printed the object passing into the function that is failing, with and without Photon, looks like Photon is removing empty strings from any object once imported (or something), investigating further. 

https://www.diffchecker.com/FgTyC3bl (left is with Photon)

**Comment by divyenduz** [comment] 2019-12-27 11:51
I found (sub part) the part of Photon that is causing this, it is most likely the residue from some dependency. I will leave this for @timsuchanek to comment on as he has more context of all the dependencies: 

https://divyendu.s3-eu-west-1.amazonaws.com/photonjs-296.mp4

**Comment by jwulf** [comment] 2020-01-06 23:14
You could compare the package.json with Photon installed and not. We found another issue where installing kafka-node alongside zeebe-node pulls in an older version of `long` that breaks gRPC functionality.

**Comment by timsuchanek** [comment] 2020-01-07 15:39
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Closed by timsuchanek** 2020-01-07 15:39 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by tvvignesh** [comment] 2020-01-07 15:53
@timsuchanek Great! Will check and get back to you if there are issues!
