### ISSUE TITLE
Enum from MySQL are undefined

### ISSUE THREAD

**Issue by tristancaron** [prisma/photonjs#63] opened 2019-06-26 13:36 UTC
Introspecting MySQL database works well, but when using a generated Photon client, if a column is an Enum, it will return undefined.

**Comment by divyenduz** [comment] 2019-06-28 11:33
@tristancaron : Can you share a minimal reproduction for this? Like how does your datamodel look like?

**Comment by pantharshit00** [comment] 2019-06-28 15:45
I can't reproduce this with the following datamodel and code: 

```grovvy
datasource db {
  provider = "mysql"
  url      = "mysql://root:Harshit00@localhost:3306/issue_60"
}

generator photon {
  provider = "photonjs"
}

enum Priviliages {
  ADMIN
  USER
}

model User {
  id          String      @id @default(cuid())
  username    String      @unique
  password    String
  age         Int         @default(18)
  priviliages Priviliages
}
```

```js
// @ts-check
const Photon = require('@generated/photon')

const photon = new Photon.default()

async function main() {
  await photon.connect()

  const res = await photon.users.findMany({
    select: {
      priviliages: true,
    },
  })
  console.log(JSON.stringify(res))
}

main()
  .then(async () => {
    await photon.disconnect()
  })
  .catch(async () => {
    await photon.disconnect()
  })

```

![image](https://user-images.githubusercontent.com/22195362/60354463-e29ed300-99e9-11e9-9cd2-12d9c5f73d92.png)

**Comment by tristancaron** [comment] 2019-06-28 16:17
Here a project that is not working for me.

I added the file `schema.sql` that we do use for the moment.

Once it's all set up, I run:
`prisma2 introspect --mysql-db orion --mysql-host 127.0.0.1 --mysql-port 3306 --mysql-user root --mysql-password admin`

I move the file generated into `prisma/project.prisma` and add the lines:
```
generator photon {
  provider = "photonjs"
}
```

Then I run
`prisma2 generate`

And finally
`node index.js`

We don't use `Lift` for the moment, it is not "stable" enough for our Alpha product. But I guess it's another topic. (In case you wonder, we have naming issues for the relations tables, and migration doesn't work well, so the first time we run `prisma2 dev` it's okay, but the second time, even we don't do any changes, it fails)

I hope it will help!

[issue_63.zip](https://github.com/prisma/photonjs/files/3340003/issue_63.zip)

**Comment by pantharshit00** [comment] 2019-06-28 16:20
Ok, got it. We just merged a fix for this.

https://github.com/prisma/photonjs/commit/6f7d983493f6bfe83c5841e8ff0598a4a42019af

**Closed** 2019-06-28 16:20 UTC
Labels: bug/0-needs-info, team/engineering
