### ISSUE TITLE
Order by related fields

### ISSUE THREAD

**Issue by alan345** [prisma/photonjs#303] opened 2019-11-20 18:04 UTC
Example: a User has many Posts. Should be possible to order the Posts by User name.

Maybe:
```
query {
  allPosts(orderByRelated: [user_name_ASC]) {
    id
  }
}
```

related to this issue with Prisma1: https://github.com/prisma/prisma/issues/95

**Comment by glen-84** [comment] 2020-01-09 09:15
Duplicate of #108.

**Comment by pantharshit00** [comment] 2020-01-21 15:43
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #108 

Also, thanks to @glen-84 for pointing out the related issue

**Closed by pantharshit00** 2020-01-21 15:43 UTC
Labels: kind/feature
