### ISSUE TITLE
Prisma errors render weird (contain \u000 characters)

### ISSUE THREAD

**Issue by momakes** [prisma/photonjs#235] opened 2019-09-24 09:38 UTC
This is the error I get:
```{ [GraphQLError:
Invalid `photon.()` invocation in /Users/mo/dev/there3/api/build/index.js:464:37



Reason: Error in connector: Record does not exist.
]
  message:
   '\n\u001b[31mInvalid \u001b[1m`photon.()`\u001b[22m invocation in \u001b[4m/Users/mo/dev/there3/api/build/index.js:464:37\u001b[24m\u001b[39m\n\n\n\n\u001b[31m\u001b[1mReason: \u001b[22m\u001b[39m\u001b[31mError in connector: Record does not exist.\u001b[39m\n\u001b[31m\u001b[39m',
  locations: [ { line: 2, column: 3 } ],
  path: [ 'currentUser' ],
  extensions:
   { code: 'INTERNAL_SERVER_ERROR',
     exception: { stacktrace: [Array] } } }

```
In terminal: 
![image](https://user-images.githubusercontent.com/55196141/65500561-5575f800-decc-11e9-8006-625aba2db67f.png)

In Playground: 
![image](https://user-images.githubusercontent.com/55196141/65500584-5dce3300-decc-11e9-8dcc-8c860c250e85.png)

**Comment by divyenduz** [comment] 2019-09-25 12:59
@momakes Thanks for raising this issue, closing it as a duplicate of https://github.com/prisma/photonjs/issues/195

Those are ANSI characters that makes Photon's output in the shell colorful etc. For now, you can pass Photon's error through a strip ANSI lib (https://www.npmjs.com/package/strip-ansi)

This spec (not implemented yet) talks about this more https://github.com/prisma/specs/tree/master/photonjs#error-handling

**Closed by divyenduz** 2019-09-25 12:59 UTC
